name=input("what is your name? ")
address=input("address :")
city=input("city :")
pincode=input("pincode :")
age=input("age :")
weight=input("weight :")
height=input("height :")
gender=input("gender :")

print(name)
print(address)
print(city)
print(pincode)
print(age)
print(weight)
print(height)
print(gender)